wiki = "ttt2"
template = "nouwiki-default-template"

[targets]
default = "dynamic"
dynamic = true
static = true
filesystem = true

[include]
import = []
css = []
js = []

[extras]
fragments = true

[[plugins.parser]]
	name = "markdown-it-nouwiki-wikilink.min.js"
		[plugins.parser.options.dynamic]
		head = "/wiki/dynamic/"
		tail = ""
		[plugins.parser.options.static]
		head = "/wiki/static/"
		tail = ""
		[plugins.parser.options.filesystem]
		head = ""
		tail = ".html"
		[plugins.parser.options.filesystem_index]
		head = "wiki/filesystem/"
		tail = ".html"
